theme = "gruvbox_dark_hard"

[editor]
mouse = true
idle-timeout = 500 # show auto-completion after 500ms
auto-format = true
auto-save = true

[editor.soft-wrap]
enable = true

[editor.lsp]
enable = true
display-signature-help-docs = false
auto-signature-help = false
display-inlay-hints = false
snippets = false


[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
