theme = "gruvbox_dark_hard"

[editor]
mouse = false
idle-timeout = 500 # show auto-completion after 500ms
auto-format = true
auto-save = true

[editor.soft-wrap]
enable = true

[editor.lsp]
display-signature-help-docs = false


[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
