[[language]]
name = "rust"
auto-format = true

[language.config]
diagnostics.disabled = [ "inactive-code" ]

# [language.language-server]
# command = "rustup"
# command = ""
# args = ["run", "nightly", "rust-analyzer"]
