#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


sh /home/simon/.screenlayout/layout.sh
xrandr --output DP-0 --mode 1920x1080 --rate 360.00 &

feh --bg-fill /home/simon/Pictures/wallpapers/space.jpg
sh /home/simon/.config/polybar/launch.sh &

xset r rate 300 100

bspc monitor DP-0 -d I II III IV V VI VII 
bspc monitor HDMI-0 -d VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Alacritty desktop='^1' follow=on
bspc rula -a spotify desktop='^8' follow=off
bspc rule -a Chromium desktop='^3' follow=on

bspc rule -a "Signal Beta" desktop='^6' follow=off
bspc rule -a thunderbird desktop='^6' follow=off
bspc rule -a spotify desktop='^8' follow=off
bspc rule -a discord desktop='^6' follow=off

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


