#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


sh /home/simon/.screenlayout/layout.sh
xrandr --output DP-0 --mode 1920x1080 --rate 360.00 &

feh --bg-fill /home/simon/Pictures/wallpapers/space.jpg
sh /home/simon/.config/polybar/launch.sh &

bspc monitor DP-0 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

